### ISSUE TITLE
ImportError: No module named googlemaps

### ISSUE THREAD

**Issue by moonpockets** [PokemonGoF/PokemonGo-Auto-Pokestop#1]
Tried running the command

> pokecli.py -a ptc -u ****** -p ****** -l "XX.xxxxxx -XX.xxxxxx"

and got this error

Traceback (most recent call last):
  File "C:\Users\Daniel\Desktop\Pokemon GO\AutoPokestop\pokecli.py", line 34, in
 <module>
    import working
  File "C:\Users\Daniel\Desktop\Pokemon GO\AutoPokestop\working.py", line 3, in
<module>
    import googlemaps
ImportError: No module named googlemaps

What am I doing wrong?

**Comment by moonpockets** [comment]
Fixed by using "pip install googlemaps" in command line.

**Comment by PokemonGoF** [comment]
yes, just added the requirement in the requirements.txt
https://github.com/PokemonGoF/PokemonGo-Auto-Pokestop/commit/45464d0171b3901bb6e45c2ce0e3800d19e7a988
